### ISSUE TITLE
execution reverted error for web3.py

### ISSUE THREAD

**Issue by xingmegshuo** [iRhonin/rarity-bot#2]
hello, when i try run it             
`python`
- adventure_txn = self.contract.functions.adventure(self.summoner_id,).buildTransaction({'nonce': self.nonce()})

buildTransaction error

**Comment by iRhonin** [comment]
Can you please attach a screenshot of the error?

**Comment by xingmegshuo** [comment]
> 你能附上错误的截图吗？

![image](https://user-images.githubusercontent.com/33823011/139177530-fba2eca9-1f41-451c-99d8-a04ebbfaa8fe.png)

maybe function buildTransaction less a param gas

**Comment by iRhonin** [comment]
I could not reproduce this error,
`execution reverted` means there is a `logical error` on the contract method execution.
Have you changed the contract address? If you did, you need to change the ABI and function parameters too.

@xingmegshuo

**Comment by xingmegshuo** [comment]
> I could not reproduce this error, `execution reverted` means there is a `logical error` on the contract method execution. Have you changed the contract address? If you did, you need to change the ABI and function parameters too.
> 
> @xingmegshuo

i have not changed contract address

> RARITY_ADRRESS = '0xce761d788df608bd21bdd59d6f4b54b2e27f25bb'

i just set my MateMask address and privite key in the .env file.

i went to see the contract functions,the parameters is same too,and view the document for web3.py ,function buildTransaction parameter nonce mean 'the current nonce for an account' , i will try to fix it .
finally,thank you for your reply ! i will contact you if i meet orther problems

**Comment by iRhonin** [comment]
Please let me know what did you for fixing it, or even open a PR if you liked. 

> > I could not reproduce this error, `execution reverted` means there is a `logical error` on the contract method execution. Have you changed the contract address? If you did, you need to change the ABI and function parameters too.
> > @xingmegshuo
> 
> i have not changed contract address
> 
> > RARITY_ADRRESS = '0xce761d788df608bd21bdd59d6f4b54b2e27f25bb'
> 
> i just set my MateMask address and privite key in the .env file.
> 
> i went to see the contract functions,the parameters is same too,and view the document for web3.py ,function buildTransaction parameter nonce mean 'the current nonce for an account' , i will try to fix it . finally,thank you for your reply ! i will contact you if i meet orther problems

**Comment by xingmegshuo** [comment]
![image](https://user-images.githubusercontent.com/33823011/139413630-83165da6-4d33-4f7e-9ade-21d3647d4780.png)
after adding a GAS parameter it can work properly

@iRhonin
